### ISSUE TITLE
Could you please update the line in the instruction

### ISSUE THREAD

**Issue by Marycka9** [adv4000/s3fs-linux#1]
Thank you for you guide, it is so helpful for me! At previous  time I've spent 

Could you please update the command for the next line:

Source:
`echo "s3fs#$BUCKET $MOUNT fuse allow_other,nonempty,use_path_request_style,iam_role=auto,url=https://s3-$REGION.amazonaws.com,endpoint=$REGION 0 0" >> /etc/fstab`

To the next command (added _netdev to the command):

`echo "s3fs#$BUCKET $MOUNT fuse _netdev,allow_other,nonempty,use_path_request_style,iam_role=auto,url=https://s3-$REGION.amazonaws.com,endpoint=$REGION 0 0" >> /etc/fstab`

My instance based on Amazon Linux 2023
Currently I've got an error after reboot (in syslog): s3fs_init could not load IAM role name from meta data

I've added the _netdev (found the solution here: https://serverfault.com/questions/441691/how-to-make-s3fs-work-with-iam-roles) and it works!

**Comment by adv4000** [comment]
Please submit PR
